### ISSUE TITLE
Service worker registration error & insecure origins are not loaded

### ISSUE THREAD

**Issue by Viktorminator** [PolymerX/polymer-skeleton#68] opened 2017-10-22 21:42 UTC
I'm using Mac OS El Capitan, latest Chrome, yarn goes without any issues in terminal and no errors so far.
In Chrome console I got next errors:
```
(index):70 Error during service worker registration: DOMException: Only secure origins are allowed (see: https://goo.gl/Y0ZkNV).
(anonymous) @ (index):70
Promise rejected (async)
(anonymous) @ (index):69
(index):86 GET http://0.0.0.0:3000/module.bundle.js net::ERR_ABORTED
```
I'd changed localhost address and set enable to _allow-insecure-localhost_ flag.
What is wrong with my installation? 
Thanks!

**Comment by LasaleFamine** [comment] 2017-10-23 09:51
Hi @Viktorminator, thank you for you interest on the repo.
Can I ask you if you are using `http://localhost:3000` or `http://yourIp:3000`?

**Comment by Viktorminator** [comment] 2017-10-23 10:01
Hey, @LasaleFamine , I tried http://localhost:3000, http://0.0.0.0 & http://myurl:3000, http://127.0.0.1:3000 with no success (I changed each time host: '0.0.0.0' in webpack.config.js)

**Comment by LasaleFamine** [comment] 2017-10-23 10:37
Are you using the `webpack-dev-server` also for exposing the `build`? Can you try with [`http-server`](https://www.npmjs.com/package/http-server) and see what happens? Actually the [registration should work on localhost...](https://stackoverflow.com/a/44547197)

**Comment by Viktorminator** [comment] 2017-10-23 16:48
http-server didn't help, but when I launch `polymer serve` in `dist` folder - everything works flawlessly and if I do the same with `http-server` - after first reload page are loaded as planned.

**Comment by LasaleFamine** [comment] 2017-10-23 18:55
I'm trying to reproduce the error. I'm on Mac OS Sierra and latest Chrome (but I'm testing it also on Safari and Firefox).

The steps I made:
* Clone the repo from here
* Run `yarn install` (`yarn 1.2.0`) within the folder of the skeleton
* Run `yarn build`
* Run `http-server dist` (I have installed `http-server` globally)
* Go on http://localhost:8080 on every browsers without errors

I can also see the correct registration inside the Application Chrome Dev Tools tab. 
Can you tell me more about your setup? I'm sorry you are having trouble with this!

**Comment by Viktorminator** [comment] 2017-10-23 19:58
hey, I tried one more time `yarn dev` and check Mozilla firefox - works fine, because of no service workers' support. Safary and Chrome - failed. ![image](https://lh6.googleusercontent.com/rnAcSn4ihY-jrlF2H078B8YcMRN87mv-VSK-Dgz1sD8xpJAWpFpErqnb2V8elhS4v-OZUc87PzU4eqY=w1906-h925-rw)
BUT! When I tried `http-server dist` - worked like a charm in all browsers 😎 . Please check if you clear all cache when run `yarn dev`.
Thank you @LasaleFamine for your time!

**Comment by LasaleFamine** [comment] 2017-10-23 20:35
Maybe I'm getting your problem. If you are running `yarn dev`, service workers are not generated. This because I'm trying to understand better how to work with Workbox in a development environment. 
If you run `yarn dev` you will get the error of failed registration, but this is just because there is no `sw.js` loaded from the `webpack-dev-server` and the `index.html` has a script that tries to load the `sw.js`. 
I should specify this on the README before the fix.

No problem for me, let the issue open until you are sure about your problem, maybe I'm wrong.

**Comment by Viktorminator** [comment] 2017-10-23 20:40
I'm very new to service workers & webpack, so if you say so about the problem &dash; I agree 👍 . I'll try to develop in Firefox with `yarn dev`. Deployment goes without any issues.

**Comment by LasaleFamine** [comment] 2017-12-04 22:42
@Viktorminator I'm closing this one. If you have any other problem let me know 👍

**Closed by LasaleFamine** 2017-12-04 22:42 UTC
